name: Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Construir proyecto con Maven
        run: mvn -B package --file EPO2/frontend-spring/pom.xml

      - name: Ejecutar tests
        run: mvn test --file EPO2/frontend-spring/frontend/pom.xml